apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arnica-k8s-collector.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "arnica-k8s-collector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [namespaces, nodes, pods, services, serviceaccounts, configmaps, persistentvolumeclaims, persistentvolumes]
    verbs: [get, list, watch]
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [get, list, watch]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses, networkpolicies]
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [httproutes]
    verbs: [get, list, watch]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, clusterroles, rolebindings, clusterrolebindings]
    verbs: [get, list, watch]
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: [get, list, watch]
  - apiGroups: [keda.sh]
    resources: [scaledobjects, scaledjobs]
    verbs: [get, list, watch]
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [get, list, watch]
  - apiGroups: [kustomize.toolkit.fluxcd.io]
    resources: [kustomizations]
    verbs: [get, list, watch]
  - apiGroups: [helm.toolkit.fluxcd.io]
    resources: [helmreleases]
    verbs: [get, list, watch]
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [gitrepositories]
    verbs: [get, list, watch]
  {{- with .Values.extraRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "arnica-k8s-collector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arnica-k8s-collector.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arnica-k8s-collector.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: kubernetes.io/service-account-token
